config/routes.rb
# Rails.application.routes.draw do
  
#   get 'static_pages/splash'
#   # get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
#   root to: 'static_pages#splash'
#   devise_for :users
#   resources :users, only: [:index, :show, :new] do
#     resources :categories, only: [:new, :create, :show, :index, :destroy]
#   #   resources :purchases, only: [:new, :create, :index, :show, :destroy]
#   end
# end

Rails.application.routes.draw do
  root to: 'static_pages#splash'
  get 'static_pages/splash'

  devise_for :users
  resources :categories, only: [:new, :index, :show, :create] do
    resources :purchases, only: [:new, :create, :index, :show, :destroy]
  end  
   end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(current_user)
    user = current_user || User.new

    can :manage, Category, user_id: user.id
    can :manage, Purchase, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :icon, presence: true

  has_many :category_purchases, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :purchases, through: :category_purchases
end

app/models/category_purchase.rb
class CategoryPurchase < ApplicationRecord
  belongs_to :category
  belongs_to :purchase
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  has_many :category_purchases
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :categories, through: :category_purchases
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :categories
  has_many :purchases, foreign_key: 'author_id'
  has_many :category_purchases, through: :purchases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!, unless: -> { request.path == '/' && request.get? }
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @author = current_user
    @categories = Category.all
    @category_sums = {}
    @categories.each do |category|
      @category_sums[category.id] = category.purchases.sum(:amount)
    end
  end

  def new
    @category = Category.new
  end

  def create
    @author = current_user
    @category = @author.categories.build(author_id: current_user.id, **category_params)
    if @category.save
      flash[:success] = 'Successfully added your category!.'
      redirect_to categories_path(@author)
    else
      flash[:error] = 'There was an error while creating the category.'
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/category_purchases_controller.rb
# File name: category_purchases_controller.rb
class CategoryPurchasesController < ApplicationController
  def index; end

  def show; end

  def new; end

  def create; end

  def destroy; end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :find_category, only: %i[new create show]

  def index
    @category = Category.find_by(id: params[:category_id])
    @category_name = @category.name
    @purchases = @category.purchases.order(created_at: :desc)
    @sum = @purchases.sum(:amount)
  end

  def new
    @purchase = Purchase.new
    @categories = Category.all
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.author_id = current_user.id

    existing_purchase = @category.purchases.find_by(name: @purchase.name, amount: @purchase.amount)

    if existing_purchase
      flash[:error] = 'A similar purchase already exists for this category.'
      redirect_to category_purchases_path(category_id: @category.id)
      return
    end

    if @purchase.save
      CategoryPurchase.create(purchase: @purchase, category_id: @category.id)

      flash[:success] = 'Successfully captured payment.'
      redirect_to category_purchases_path(category_id: @category.id)
    else
      flash[:error] = 'There was an error while capturing the payment.'
      render :new
    end
  end

  private

  def purchase_params
    params.require(:purchase).permit(:name, :amount)
  end

  def find_category
    @category = Category.find_by(id: params[:category_id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def splash
    # render :splash
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/index.html.erb
<header class="header-cat">
<nav class="category-nav">
<i class="fas fa-bars"></i>
<h1>Categories</h1>
<i class="fas fa-search"></i>
</nav>
</header>
<section class="category-container">
<% if @categories.empty? %>
<p>Please add categories to see here, currently there are no categories for the budget</p>
<% else %>
<% @categories.each do |category| %>
    <article class="category-article">
    <%= link_to category_purchases_path(category.id) do %>
      <div class="article-inner">
   <div class="icon">
  <img src="<%= category.icon %>" class="category-icon" alt="<%= category.name %>" />
</div>
    <div class="name-category"><%= category.name %></div>
    <div class="total-category"><span class="total-span">$<%= @category_sums[category.id] %></span></div>
    </div>
    <% end %>
</article>
<% end %>
    <% end %>
    <div class="add-category-btn">
    <%= link_to "Add new Category", new_category_path, class: "add-category" %>
  </div>
</section>

app/views/categories/new.html.erb
<header class="header-cat">
<nav class="category-nav">
<%= link_to categories_path(current_user) do %>
  <i class="fas fa-less-than"></i>
  <% end %>
<h1>New Category</h1>
<i class="fas fa-search"></i>
</nav>
</header>
<div class="category-container-new">
<%= form_with(model: @category, url: categories_path) do |form| %>
    <div class="form-food">
   
  <div class="label-category">
    <%= form.text_field :name, class: "name-1", placeholder: "Name" %>
    <%= form.text_field :icon, class: "icon-field", placeholder: "Icon"  %>
  </div>
  <div class="category-submit-btn">
    <p><%= form.submit "Save", class: "new-category-btn" %></p>
  </div>
  </div>
<% end %>
<div>

app/views/categories/show.html.erb
this is show 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyTrackerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/purchases/_index.html.erb
<p>Find me in app/views/purchases/index.html.erb</p>

app/views/purchases/create.html.erb
<p>Find me in app/views/purchases/create.html.erb</p>

app/views/purchases/destroy.html.erb
<p>Find me in app/views/purchases/destroy.html.erb</p>

app/views/purchases/index.html.erb
<%# <local_assigns > %>
<header class="header-payment">
<nav class="nav-payment">
<%= link_to categories_path(current_user) do %>
<i class="fas fa-less-than"></i>
<% end %>
<h1>Payments</h1>
<i class="fas fa-search"></i>
</nav>
<div class="recent-content">
<p class="p1">Most recent <span>.</span></p>
<p class="p2">Most Ancient <span>&nbsp;</span></p>
</div>
</header>
<section class="payments-section">
<div class="top">
<p><%= @category_name %></p>
<h3>$<%= @sum %></h3>
</div>
<% if @purchases.empty? %>
<p>There are no payments for this category</p>
<% else %>
<% @purchases.each do |purchase| %>
    <article class="payment-article">
    <div class="payment-div">
    <%=image_tag(@category.icon, :alt => "category icon.", :class => "category-payment-icon") %>
<p class="pay-name"><%= purchase.name %></p>
<h4>$<%= purchase.amount %></h4>
</div>
<div class="date-div">
<p class="pay-date"><%= purchase.created_at.strftime('%Y-%m-%d') %></p>
</div>
    </article>
    <% end %>
    <% end %>
    <div class="add-transaction">
    <%= button_to "Add a payment", new_category_purchase_path(@category), method: :get, class: "add-payment" %>
    </div>
</section>

app/views/purchases/new.html.erb
  <header class="header-cat">
<nav class="category-nav payment-nav">
<%# <link_to user_categories_path(current_user) do > %>
    <%= link_to categories_path(@category) do %>
  <i class="fas fa-less-than"></i>
  <% end %>
<h1>Add new payment</h1>
<i class="fas fa-search"></i>
</nav>
</header>

<div class="new-payment-container">
<%= form_with(model: @purchase, url: category_purchases_path(@category, category_id: @category.id), method: :post) do |f| %>

    <div class="label-payment">
      <%= f.text_field :name, class: "form-control", placeholder: "Name", required: true %>
    <%= f.number_field :amount, class: "form-control", placeholder: "Amount", required: true %>
  </div>
  <div class="categories-form-cont">
  <%= f.label :category_ids, "Categories", class: "all-categories-label" %>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <div class="form-check">
      <%= cb.check_box(class: "form-check-input") %>
      <%= cb.label(class: "form-check-label") %>
    </div>
  <% end %>
</div>
    <div class="payment-submit-btn">
      <%= f.submit "Save", class: "new-payment-btn" %>
    </div>
  <% end %>
  </div>

app/views/static_pages/splash.html.erb
<section class = "Home-section">
 <div class = "home-cont">
  <h1> LellouLV</h1>
    <div class="links-btns">     
       <button class = "home-button" ><%= link_to "LOGIN", new_user_session_path %></button>
       <button class = "home-button"><%= link_to "SIGN UP", new_user_registration_path %></button>
    </div>
 </div>
</section>